name: Automatic e2e Regression Trigger
on:
    issue_comment:
        types: [created]

jobs:
    prepare:
        runs-on: ubuntu-latest
        if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/regression')
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: pr
              run: |
                  echo "NAME_SUFFIX=-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
                  echo "NAMESPACE=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
            - name: Run a one-line script
              run: echo Hello, world!
