name: Manual Regression Trigger
on:
  issue_comment:
    types: [created]

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/regression')
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
            ref: refs/pull/${{ github.event.issue.number }}/head

  end-to-end-tests:
        needs: [prepare]
        uses: ./.github/workflows/e2e.yaml
        with:
            ref: refs/pull/${{ github.event.issue.number }}/head
