name: Manual Regression Trigger
on:
  issue_comment:
    types: [created]

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/regression')
    steps:
      - name: Get PR details
        id: pr_details
        run: |
          PR_DATA=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                         -H "Accept: application/vnd.github.v3+json" \
                         https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.issue.number }})

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.pr_details.outputs.repo }}
          ref: ${{ steps.pr_details.outputs.head.ref }}
          run: echo "${{ steps.pr_details.outputs.head.ref }}"
          fetch-depth: 0

      - id: print_branch
        run: |
          echo "${{ steps.pr_details.outputs }}" >> $GITHUB_OUTPUT


  end-to-end-tests:
    needs: [prepare]
    uses: ./.github/workflows/e2e.yaml
    with:
      ref: refs/pull/${{ github.event.issue.number }}/merge
