name: Manual Regression Trigger
on:
  issue_comment:
    types: [created]

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/regression')
    steps:

      - name : end-to-end-tests
        uses: ./.github/workflows/e2e.yaml
        with:
            ref: refs/pull/${{ github.event.issue.number }}/head
