name: e2e-tests

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - name: print ref
        run: echo "${{ inputs.ref }}"

      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}
      
      - name: print github ref
        run: echo "${{ github.ref }}"
       
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v8
